#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
from geometry_msgs.msg import Twist


# Inicializar el nodo
rospy.init_node('movimiento_robot')

# Declarar del publicador
topic = 'cmd_vel'
pub = rospy.Publisher(topic, Twist, queue_size=10)
# Creación de una instancia (vacía) del mensaje
twist = Twist()

# Tiempo de ejecución del bucle (en Hz)
rate = rospy.Rate(12)

counter = 0
while not rospy.is_shutdown():
    # Asignar los valores al mensaje
    # Primera Linea  
    if counter > 0 and counter < 300:
        twist.linear.x = 10.0
        twist.linear.y = 10.0
        twist.linear.z = 0.0
        twist.angular.x = 0.0
        twist.angular.y = 0.0
        twist.angular.z = 0.0   

    if counter > 300 and counter < 400:
        twist.linear.x = 10.0
        twist.linear.y = 10.0
        twist.linear.z = 0.0
        twist.angular.x = 5.0
        twist.angular.y = 5.0
        twist.angular.z = 0.0

    if counter > 1000:
        twist.linear.x = 15.0
        twist.linear.y = 15.0
        twist.linear.z = 0.0
        twist.angular.x =0.0
        twist.angular.y =0.0
        twist.angular.z =0.0
    
    counter+=1
    # Publicar el mensaje
    pub.publish(twist)
    # Esperar
    rate.sleep()